PqrsdfApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.contrib.auth.decorators import login_required
from apps.pqrsdf.views import Home, Dashboard, CreatePqrsdfUser, GetPqrsdfView
from apps.user.views import Login, logoutUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='index'),
    path('dashboard/', login_required(Dashboard.as_view()), name='dashboard'),
    path('dashboard/pqrsdf/', include(('apps.pqrsdf.urls', 'pqrsdf'))),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', login_required(logoutUser), name='logout'),
    path('create_pqrsdf/', CreatePqrsdfUser.as_view(), name='create_pqrsdf'),
    path('get_pqrsdf/<str:radicated>/', GetPqrsdfView.as_view(), name='get_pqrsdf')
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

apps/pqrsdf/models.py
from django.db import models
from apps.user.models import User
from datetime import datetime, timezone, date
from workalendar.america import Colombia

cal = Colombia()
# Create your models here.

class Pqrsdf(models.Model):
    STATE_OPTIONS = (
        (1, "Radicación"),
        (2, "Elaboración"),
        (3, "Revisión"),
        (4, "Finalizado"),
    )
    TYPE_PQRSDF = (
        (1, "Petición"),
        (2, "Queja/Reclamo"),
        (3, "Solicitud de información"),
        (4, "Denuncia"),
        (5, "Sugerencia/Propuesta")
    )
    TYPE_IDENTIFICATION = (
        (1, "Cédula de ciudadanía"),
        (2, "NUIP"),
        (3, "Cédula de extranjería"),
        (4, "NIT"),
        (5, "Pasaporte")
    )
    MEDIUM_CONTACT = (
        (1, "Correo electrónico"),
        (2, "Dirección de correspondencia"),
    )
    active = models.BooleanField(verbose_name="Activo", default=True)
    radicated = models.CharField(
        verbose_name="Radicado", max_length=50, blank=True, null=True)
    date_pqrsdf = models.DateTimeField(verbose_name="Fecha", auto_now_add=True)
    state_actual = models.IntegerField(verbose_name="Estado",
                             choices=STATE_OPTIONS, default=1)
    days_passed = models.IntegerField(verbose_name="Tiempo transcurrido", blank=True, null=True)
    type_pqrsdf = models.IntegerField(
        choices=TYPE_PQRSDF, verbose_name="Tipo de PQRSDF")
    type_anonymous = models.BooleanField(blank=True, null=True)
    name = models.CharField(
        max_length=30, verbose_name="Nombre", blank=True, null=True)
    type_identification = models.IntegerField(
        choices=TYPE_IDENTIFICATION, verbose_name="Tipo de identificación", blank=True, null=True)
    identification = models.CharField(
        max_length=30, verbose_name="Identificación", blank=True, null=True)
    medium_contact = models.IntegerField(
        choices=MEDIUM_CONTACT, verbose_name="Medio de contacto", blank=True, null=True)
    email = models.CharField(
        max_length=200, verbose_name="Correo electrónico", blank=True, null=True)
    correspondence_address = models.CharField(
        max_length=200, verbose_name="Dirección de correspondencia", blank=True, null=True)
    neighborhood = models.CharField(
        max_length=200, verbose_name="Barrio / Vereda / Corregimiento", blank=True, null=True)
    municipality = models.CharField(
        max_length=200, verbose_name="Municipio / Distrito", blank=True, null=True)
    country = models.CharField(
        max_length=200, verbose_name="País", blank=True, null=True)
    number_contact = models.CharField(
        max_length=30, verbose_name="Número de contacto", blank=True, null=True)
    description = models.TextField(verbose_name="Descripción")
    file_id = models.ForeignKey('PqrsdfFile', verbose_name="Adjunto", related_name='pqrsdf_files', on_delete=models.CASCADE, null=True, blank=True)
    
    class Meta:
        verbose_name = "Pqrsdf"
        verbose_name_plural = "Pqrsdf"
        
    @staticmethod
    def filter_by_type(type_pqrsdf):
        return Pqrsdf.objects.filter(type_pqrsdf=type_pqrsdf)
    
    @staticmethod
    def filter_by_state(state_actual):
        return Pqrsdf.objects.filter(state_actual=state_actual)
    
    @property
    def days_since_created(self):
        """
        Calcula los días transcurridos desde la creación del objeto `Pqrsdf` hasta la fecha actual.
        """
        if not self.date_pqrsdf:
            return 0
        days_passed = cal.get_working_days_delta(self.date_pqrsdf.date(), date.today())
        return days_passed #Compara con 0 y así nunca regresa un número negativo

    def __str__(self):
        return str(self.type_pqrsdf)

class PqrsdfFile(models.Model):
    pqrsdf = models.ForeignKey(Pqrsdf, on_delete=models.CASCADE)
    file = models.FileField(upload_to='pqrsdf_files/')
    
    class Meta:
        verbose_name = "PqrsdfFile"
        verbose_name_plural = "PqrsdfFile"
    
    def __str__(self):
        return f"{self.id}"
        
    @property
    def file_url(self):
        return self.file.url


class PqrsdfState(models.Model):
    id_pqrsdf = models.ForeignKey(
        Pqrsdf, on_delete=models.CASCADE, verbose_name="Id pqrsdf")
    state = models.IntegerField(choices=Pqrsdf.STATE_OPTIONS, default=1)
    date_previous_change = models.DateTimeField(verbose_name="Fecha anterior",null=True)
    date_change = models.DateTimeField(
        verbose_name="Fecha Actual", null=True, blank=True, auto_now=True)
    user_previous_change = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario Anterior', null=True, related_name='%(class)s_previous_change')
    user_change = models.ForeignKey(User, on_delete=models.PROTECT,verbose_name="Usuario Actual", related_name='%(class)s_change', null=True)

    class Meta:
        verbose_name = 'PqrsdfState'
        verbose_name_plural = "PqrsdfStates"
    
        
    def __str__(self):
        return self.get_state_display()


class ResponsePqrsdf(models.Model):
    pqrsdf = models.ForeignKey(Pqrsdf, on_delete=models.CASCADE, verbose_name='Respuesta')
    date_creation = models.DateTimeField(auto_now_add=True)
    response = models.TextField(blank=True)
    user_response = models.ForeignKey(User, on_delete=models.PROTECT,verbose_name="Usuario")
    
    class Meta:
        verbose_name = "Response"
        verbose_name_plural = "Responses"

templates/create_pqrsdfUser.html
{% extends 'index.html' %}{% load static %}{% block containerHome %}
<div class="container-form-create-user">
  <form method="POST" class="form-horizontal form-create-user">
    {% csrf_token %}
    <div
      id="myModal"
      class="modal fade"
      tabindex="-1"
      role="dialog"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header"><h3>Creación Exitosa PQRSDF</h3></div>
          {% comment %} <span class="close">&times;</span> {% endcomment %}
          <div class="modal-body">
            <h5>Se ha creado la PQRSDF con éxito.</h5>
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary close"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button
              id="acceptBtn"
              class="btn btn-primary"
              data-dismiss="modal"
              type="button"
            >
              Aceptar
            </button>
          </div>
        </div>
      </div>
    </div>
    {% if error%}
    <h2>{{error}}</h2>
    {% else %}
    <div class="card">
      <div class="card-header">
        <strong class="card-title">Crear PQRSDF</strong>
      </div>
      <div class="card-body">
        <span>
          Los campos que tienen <span style="color: red">*</span> Son
          obligatorios
        </span>
        <br />
        <br />
        <div class="row form-group">
          <div class="col-12 col-md-12">
            {% for field in form %} {{ field.errors }}
            <div id="{{field.id_for_label}}" class="form-group-input">
              {{ field.label_tag }} {{field}}
            </div>
            {% endfor %}
          </div>
        </div>
        <button id="guardarBtn" type="submit" class="btn btn-success">
          Guardar
        </button>
        <a href="{% url 'index' %}">Cancelar</a>
      </div>
    </div>
    {% endif %}
  </form>
</div>
<br />
{% endblock containerHome %}{% block extraJs %}
<script src="{% static 'js/form.js' %}"></script>
<script>
  // Aquí está el código JavaScript para mostrar el modal
  var modal = document.getElementById("myModal");
  var span = document.getElementsByClassName("close")[0];
  var form = document.querySelector("form");
  var acceptBtn = document.getElementById("acceptBtn");

  form.addEventListener("submit", function (event) {
    event.preventDefault();
    var xhr = new XMLHttpRequest();
    xhr.open(form.method, form.action, true);
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.onload = function () {
      if (xhr.status === 200) {
        // Aquí se muestra el modal
        $(modal).modal("show");
        acceptBtn.style.display = "block"; // Mostrar el botón "Aceptar"
        document.getElementById("guardarBtn").disabled = true;
      }
    };
    xhr.send(new FormData(form));
  });

  // Cuando se hace clic en la X del modal, se cierra el modal
  span.onclick = function () {
    modal.style.display = "none";
  };

  // Redirigir al hacer clic en el botón "Aceptar"
  acceptBtn.onclick = function () {
    window.location.href = "{% url 'index' %}";
  };

  $("#myModal").on("hidden.bs.modal", function () {
    $(this).remove(); // Elimina el modal del DOM
  });
</script>
{% endblock extraJs %}

templates/dashboard.html
{% extends 'index.html' %}{% load static %} {% block body %}
<!--comentario-->{% block dashboard %}
<aside id="left-panel" class="left-panel">
  <nav class="navbar navbar-expand-sm navbar-default navbar-dashboard">
    <div id="main-menu" class="main-menu collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'dashboard' %}"
            ><i class="menu-icon fa fa-laptop"></i>Dashboard
          </a>
        </li>
        <li class="menu-title">Consultas</li>
        <li>
          <a href="{% url 'pqrsdf:get_pqrsdfs' %}"
            ><i class="menu-icon fa fa-cogs"></i>PQRSDF
          </a>
        </li>
      </ul>
    </div>
  </nav>
</aside>
<div id="right-panel" class="right-panel">
  <header id="header" class="header">
    <div class="top-left">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"
          ><img src={% static 'img/logoCuraduria.png' %} alt="Logo"></a
        >
        <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
      </div>
    </div>
    <div class="top-right">
      <div class="header-menu">
        <div class="text-user-navbar">
          <p class="user-navbar"><strong>{{ user.username }}</strong></p>
        </div>
        <div class="user-area dropdown float-right">
          <a
            class="dropdown-toggle active"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            data-bs-toggle="dropdown"
          >
            <i class="fa fa-user-circle fa-3x"></i>
          </a>
          <div class="user-menu dropdown-menu">
            <a class="nav-link" href="#"
              ><i class="fa fa-user" disabled></i>{{ user.username }}</a
            >
            <a class="nav-link" href="{% url 'logout' %}"
              ><i class="fa fa-power-off"></i>Logout</a
            >
          </div>
        </div>
      </div>
    </div>
  </header>
  {% endblock dashboard %}
  <div class="content">
    {% block content %}
    <div class="row">
      <div class="col-sm-12">
        <div class="page-header float-left">
          <div class="page-title">
            <h3>Bienvenido {{ user.username }}</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-lg-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">Estado Actual PQRSDF</strong>
          </div>
          <div class="card-body">
            <div class="row">
              {% for estado, count in estado_counts.items %}
              <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                <div class="card card-state text-white bg-flat-color-1">
                  <div class="card-body">
                    <div class="card-left pt-1 float-left">
                      <h3 class="mb-0 fw-r">
                        <span class="count">{{ count }}</span>
                      </h3>
                      <p class="text-light mt-1 m-0">{{estado }}</p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                <div class="card card-state text-white bg-flat-color-1">
                  <div class="card-body">
                    <div class="card-left pt-1 float-left">
                      <h3 class="mb-0 fw-r">
                        <span class="count">23569</span>
                      </h3>
                      <p class="text-light mt-1 m-0">Radicación</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                <div class="card card-state text-white bg-flat-color-6">
                  <div class="card-body">
                    <div class="card-left pt-1 float-left">
                      <h3 class="mb-0 fw-r">
                        <span class="count float-left">85</span>
                      </h3>
                      <p class="text-light mt-1 m-0">Elaboración</p>
                    </div>
                    <!-- /.card-left -->
                    <!-- /.card-right -->
                  </div>
                </div>
              </div>
              <!--/.col-->

              <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                <div class="card card-state text-white bg-flat-color-3">
                  <div class="card-body">
                    <div class="card-left pt-1 float-left">
                      <h3 class="mb-0 fw-r">
                        <span class="count">6569</span>
                      </h3>
                      <p class="text-light mt-1 m-0">Revisión</p>
                    </div>
                    <!-- /.card-left -->
                    <!-- /.card-right -->
                  </div>
                </div>
              </div>
              <!--/.col-->
              <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                <div class="card card-state text-white bg-flat-color-2">
                  <div class="card-body">
                    <div class="card-left pt-1 float-left">
                      <h3 class="mb-0 fw-r">
                        <span class="count">1490</span>
                      </h3>
                      <p class="text-light mt-1 m-0">Finalizado</p>
                    </div>
                    <!-- /.card-left -->
                    <!-- /.card-right -->
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-4">
                <div class="card card-state text-white bg-flat-color-4">
                  <div class="card-body">
                    <div class="card-left pt-1 float-left">
                      <h3 class="mb-0 fw-r">
                        <span class="count">23569</span>
                      </h3>
                      <p class="text-light mt-1 m-0">TOTAL</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--/.col-->
        {% comment %}
        <div class="col-sm-12 col-lg-12">
          {% endcomment %}
          <div class="card">
            <div class="card-header">
              <strong class="card-title">PQRSDF</strong>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                  <div class="card card-state">
                    <div class="card-body">
                      <div class="stat-widget-four">
                        <div class="stat-icon dib">
                          <i class="ti-write text-muted"></i>
                        </div>
                        <div class="stat-content">
                          <div class="text-left dib">
                            <div class="stat-heading">Petición</div>
                            <div class="stat-text">Total: 765</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                  <div class="card card-state">
                    <div class="card-body">
                      <div class="stat-widget-four">
                        <div class="stat-icon dib">
                          <i class="ti-close text-muted"></i>
                        </div>
                        <div class="stat-content">
                          <div class="text-left dib">
                            <div class="stat-heading">Queja</div>
                            <div class="stat-text">Total: 765</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                  <div class="card card-state">
                    <div class="card-body">
                      <div class="stat-widget-four">
                        <div class="stat-icon dib">
                          <i class="ti-announcement text-muted"></i>
                        </div>
                        <div class="stat-content">
                          <div class="text-left dib">
                            <div class="stat-heading">Reclamo</div>
                            <div class="stat-text">Total: 765</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
                  <div class="card card-state">
                    <div class="card-body">
                      <div class="stat-widget-four">
                        <div class="stat-icon dib">
                          <i class="ti-alert text-muted"></i>
                        </div>
                        <div class="stat-content">
                          <div class="text-left dib">
                            <div class="stat-heading">Denuncia</div>
                            <div class="stat-text">Total: 765</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-4">
                  <div class="card card-state">
                    <div class="card-body">
                      <div class="stat-widget-four">
                        <div class="stat-icon dib">
                          <i class="ti-check text-muted"></i>
                        </div>
                        <div class="stat-content">
                          <div class="text-left dib">
                            <div class="stat-heading">TOTAL PQRSDF</div>
                            <div class="stat-text">765</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% comment %}
        </div>
        {% endcomment %}
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        {% for tipo, count in type_counts.items %}
        <div class="col-sm-6 col-md-4 col-lg-6 col-xl-6 col-xxl-2">
          <div class="card card-state">
            <div class="card-body">
              <div class="stat-widget-four">
                <div class="stat-icon dib">
                  <i class="ti-write text-muted"></i>
                </div>
                <div class="stat-content">
                  <div class="text-left dib">
                    <div class="stat-heading">{{tipo}}</div>
                    <div class="stat-text">{{count}}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endblock content %}
  <div class="clearfix"></div>
  <footer class="site-footer">
    <div class="footer-inner bg-white">
      <div class="row">
        <div class="col-sm-6">Copyright &copy; 2023 Curaduria 2</div>
        <div class="col-sm-6 text-right">Designed by Sebastián Martínez</div>
      </div>
    </div>
  </footer>
  <!-- Esto es un comentario -->
</div>
{% endblock body %} {% block extraJs %}
<script src="{% static 'js/main.js' %}"></script>
{% endblock extraJs %}

templates/get_pqrsdf.html
{% extends 'index.html' %} {% load static %} {% block containerHome %}
<div class="card">
  <div class="card-header">
    <strong class="card-title">RADICADO No. {{ pqrsdf.radicated }}</strong>
  </div>
  <div class="card-body">
    {% if pqrsdf %}
    <p>Fecha de radicación: {{pqrsdf.date_pqrsdf}}</p>
    <p>Estado: {{ pqrsdf.get_state_actual_display }}</p>
    {% else %}
    <p>{{ error_message }}</p>
    {% endif %}
    <a href="{% url 'index' %}">
      <button id="atrasBtn" type="button" class="btn btn-success">
        Atras
      </button></a
    >
  </div>
</div>
<br />
{% endblock containerHome %}

templates/login.html
{% extends 'index.html' %} {%load static%} {% block body %}
<div class="sufee-login d-flex align-content-center flex-wrap">
  <div class="container">
    <div class="login-content">
      <div class="login-logo">
        <a href="/">
          <img
            class="align-content"
            src="{% static 'img/logoCuraduria.png' %}"
            alt=""
          />
        </a>
      </div>
      <div class="login-form">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            {% if request.method == 'POST' %} {% if form.error_messages %}
            <div class="alert alert-danger alert-dismissible" role="alert">
              <strong>Advertencia: </strong> {{ form.get_invalid_login_error }}
            </div>
            {% endif %} {% endif %}
            <label>Usuario</label>
            {{form.username}}
          </div>
          <div class="form-group">
            <label>Contraseña</label>
            {{form.password}}
          </div>
          <div class="checkbox">
            <label> <input type="checkbox" /> Remember Me </label>
          </div>
          <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">
            Iniciar Sesión
          </button>
          <div class="social-login-content">
            <div class="social-button">
              <a href="{% url 'index' %}">
                <button
                  type="button"
                  class="btn social facebook btn-flat btn-addon mb-3"
                >
                  Cancelar
                </button>
              </a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock body %}